twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        dl_dir: 'assets/uploads/'

when@test:
    twig:
        strict_variables: true
